### PR TITLE
Separate exe/etl into exe/extract and exe/transform

### PR DESCRIPTION
**Pull request by jcoyne**
This saves on typing.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Should this be part of the PR? https://github.com/sul-dlss-labs/rialto-etl/pull/43/files#diff-26d8efc71155f83dbde3ff8358b3f020

**Comment by jcoyne** [comment]
@mjgiarlo I think so, I removed that class.

**Comment by mjgiarlo** [comment]
@jcoyne I am not seeing that file in `master`. It looks like this PR would add a new empty file.

**Comment by jcoyne** [comment]
@mjgiarlo Thanks. I was just looking at the wrong line in that diff. Thanks for the review.

**Pull request merged**
